### ISSUE TITLE
FaceRecognitionImage download Vgg model error 

### ISSUE THREAD

**Issue by cjj1120** [CertifaiAI/cdle-traininglabs#182]
**Describe the bug**
Can't download the complete model. Return SSL exception error. 

**To Reproduce**
1. Go to 'src/main/java/ai/certifai/solution/facial_recognition/'
2. Run 'FaceRecognitionImage.java'
3. See error

**Screenshots (Error)**
https://gist.github.com/cjj1120/417cc7368b671f386098c513d335f191

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser: Chrome

**Comment by scotgopal** [comment]
Hi there @cjj1120 . Thanks for raising this issue and I believe your issue is rather similar to [this](https://github.com/CertifaiAI/CertifAI-Knowledge-Base/issues/40) issue. I've experienced this problem in the past as well and upon probing, I realized that it was happening due to me having an unstable internet connection. The VGG model download process gets halted due to temporary loss of internet connection. The model itself is a big file so its a bummer that IntelliJ does not support download resuming.

One solution would be to directly download the model using your browser since most browsers today allow download resuming, there should be no more issue. Please refer to the guide here for the detailed steps. https://github.com/CertifaiAI/CertifAI-Knowledge-Base/wiki/Manually-Download-Pretrained-Model.

Alternatively, you can consider switching from WiFi to a wired connection (either LAN or USB Tethering should do) to avoid connection drops. Hope this helps. 😄

**Comment by cjj1120** [comment]
Yap you are right, it works now, thank you! appreciate it!
